analysis:
  site: parsed.hostname
  content:
    selector:
      - 'body.home div.layout-container'
      - 'body.talks #block-mainpagecontent > div > div.group-left > div:nth-child(2)'
      - '#root article section'
      - 'main'
  properties: 
    'content.cms':
      - 'tech.CMS.[0]'
      - 'tech.Blogs.[0]'
    'content.type':
      - data.meta.og.type
      - source: data.attributes.classes
        in:
          - people
          - events
          - talks
          - themes
          - about
        limit: 1
    'content.title':
      - data.meta.og.title
      - data.title
      - source: body
        selector: h1.page-title
    'content.date': 
      - data.schemaOrg.NewsArticle.datePublished
      - data.meta.article.published_time
      - data.info.CreationDate
      - source: body
        selector: 'div.td-presented-on > div:nth-child(2)'
      - source: body
        selector: 'header.pw-post-byline-header p.pw-published-date'
    'content.author':
      - data.schemaOrg.NewsArticle.author.name
      - data.meta.author
      - source: body
        selector: 'div.article-content div.td-presented-by > div'
      - source: body
        selector: 'header.pw-post-byline-header div.pw-author'
    'content.location': 
      - source: body
        selector: 'div.article-content div.td-location'
    'content.tags': 
      - source: body
        selector: 'div.article-content div.td-topics > div > div > a'
      - source: body
        selector: '#root main > div > div:nth-child(4) > div > div'
    'content.pages': data.info.pages
  patterns:
    - property: 'parsed.domain'
      eq: 'worldiaday.org'
      patterns:
        - name: card
          selector: 'div.grid-list-item'
        - name: filter-form
          selector: 'div.views-exposed-form'
        - name: video-embed
          selector: 'video-embed-field-responsive-video'
    - property: 'parsed.domain'
      eq: 'medium.com'
      patterns:
        - name: bio
          selector: 'header.pw-post-byline-header'
          properties:
            author:
              source: html
              selector: 'div.pw-author'
            published:
              source: html
              selector: 'p.pw-published-date'
        - name: recirc
          selector: 'main footer~div span article'
