configVersion: 0.9.22
extends:
  - ../../arango.config.yml
  - ./analyze.yml
  - ./report.yml

arango:
  databaseName: wiad
  
offloadBodyHtml: 'db'

spider:
  seed: 
    - https://worldiaday.org
    - https://medium.com/worldiaday
  maxConcurrency: 2,
  maxRequests: 240,
  saveCookies: true
  savePerformance: true
  saveXhrList: true
  auditAccessibility: true
  urls:
    regions:
      header: 'div.site--header--wrapper'
      content: 'main'
      footer: 'footer.site-footer'
    selectors:
      - a
      - iframe
      - video
      - audio
    crawl: "http*//*{worldiaday.org,medium.com/worldiaday}{*,*/**}"
  downloadMimeTypes:
    - '*/*'
