configVersion: 0.10.4
extends:
  - ../../arango.config.yml
  - ../../page-tech.json5
  - ./analysis.json5
  - ./patterns.json5
  - ./queries.json5
  - ./reports.json5
  - ./pagedetails.report.json5

arango:
  databaseName: nitropdf
  
offloadBodyHtml: 'db'

normalizer:
  forceLowercase: 'hostname'
  discardFirstSegment: 'ww*'
  supplySubdomain: 'www'
  discardAnchor: true
  discardAuth: true
  discardIndex: '**/{index,default}.{htm,html,aspx,php}'
  discardSearch: '!{page,p,category}'
  discardTrailingSlash: false
  sortSearchParams: true

spider:
  maxConcurrency: 2,
  maxRequestsPerMinute: 240,
  saveCookies: true
  savePerformance: true
  saveXhrList: true
  auditAccessibility: false
  shadowDom: false
  headless: true
  stealth: true
  urls:
    regions:
      header: 'ps-header'
      main: 'section.page__content, div.Page-content'
      footer: 'div.Page-footer'
    selectors:
      - a
      - iframe
      - video
      - audio
    crawl: 
      - "http*//*gonitro.com{*,*/**}"

  downloadMimeTypes:
    - '*/*'
