analysis:
  content:
    selector:
      - '.site-content, .ng-container'
      - '.archive-posts, main article.ng-width-large-2-3'
      - '.ng-edu-homepage-wrapper > .d-flex.container, main.container > article, main:not([class]) .col-lg-8'
      - '.post-template-default .entry-content, body:not(.post-template-default) .site-main'
      - 'article.flex-column, [data-test-id="row"]'
  properties: 
    'content.cms':
      - 'tech.CMS.[0]'
      - 'tech.Blogs.[0]'
    'content.type':
      - 'data.meta.og.type'
    'content.title':
      - 'data.meta.og.title'
      - 'data.title'
    'content.description':
      - 'data.meta.og.description'
      - 'data.meta.description'
      - 'data.schemaOrg.WebPage.description'
    'content.author':
      - 'data.meta.author'
    'content.date': 
      - 'data.schemaOrg.WebPage.datePublished'
      - 'data.meta.article.published_time'
      - 'data.info.CreationDate'
      - 'data.meta.article.modified_time'
