configVersion: 0.10.4
extends:
  - ../../arango.config.yml
  - ./analysis.json5
  - ./queries.json5
  - ./reports.json5
  - ./pagedetails.report.json5

arango:
  databaseName: dropbox
  
offloadBodyHtml: 'db'

normalizer:
  forceLowercase: 'hostname'
  discardFirstSegment: 'ww*'
  supplySubdomain: 'www'
  discardAnchor: true
  discardAuth: true
  discardIndex: '**/{index,default}.{htm,html,aspx,php}'
  discardSearch: '!{page,p,category}'
  discardTrailingSlash: false
  collapseSearchParams: page
  sortSearchParams: true

spider:
  seed: 
    - https://www.dropbox.com
  maxConcurrency: 1,
  maxRequests: 5,
  saveCookies: true
  savePerformance: true
  saveXhrList: true
  auditAccessibility: false
  shadowDom: true
  headless: true
  stealth: true
  urls:
    regions:
      header: 'header.uni-nav-container, header.u01-header__header, nav.u01-secondary-nav'
      main: 'div.main'
      footer: 'footer'
    selectors:
      - a
      - iframe
      - video
      - audio
    crawl: 
      - "http*//www.dropbox.com{*,*/**}"
      - property: href
        glob: "http*://www.dropbox.com/{static,password_expired,help/sl,help/vodafone,home,package_files_uploaded_via_chrome,photos/app_store_link,recover,sharing,sharing/folders,sharing/files,requests,account,referrals,downgrade,developers-v1,developers/downloads/sdks,developers/whats_new,reengageoptout,preview}*/**"
        reject: true

  downloadMimeTypes:
    - '*/*'
