configVersion: 0.10.4
extends:
  - ../../arango.config.yml
  - ../../page-tech.json5
  - ./analysis.json5
  - ./queries.json5
  - ./reports.json5
  - ./pagedetails.report.json5
  - ./resources.report.json5
  - ./errors.report.json5
  - ./patterns.json5

arango:
  databaseName: dropbox-eng
  
offloadBodyHtml: 'db'

normalizer:
  forceLowercase: 'hostname'
  discardFirstSegment: 'ww*'
  supplySubdomain: 'www'
  discardAnchor: true
  discardAuth: true
  discardIndex: '**/{index,default}.{htm,html,aspx,php}'
  discardSearch: '!{page,p,category}'
  discardTrailingSlash: false
  sortSearchParams: true
  replace:
    match: '/_jcr_content/root/u06_main_content/par/responsivegrid/b20_article_grid_pla.query.'
    value: '?page='

spider:
  seed:
    - https://www.dropbox.com
    - https://blog.dropbox.com
    - https://experience.dropbox.com
  saveCookies: true
  savePerformance: true
  saveXhrList: true
  auditAccessibility: false
  shadowDom: true
  headless: true
  stealth: false
  maxConcurrency: 1
  maxRequestsPerMinute: 20
  sameDomainDelaySecs: 4
  userAgent: "Screaming Frog SEO Spider/19.3 (Robots: Screaming Frog SEO Spider)"
  urls:
    regions:
      nav: 'header.u01-header__header, div.dwg-nav'
      subnav: 'nav.u01-secondary-nav'
      main: 'div#main, main#page-content, main#main-content'
      footer: 'footer.dbx-footer, footer.u02-footer, footer.contentinfo'
    selectors:
      - head link[rel="alternate"]
      - a
      - iframe
      - video
      - audio
    crawl: 
      - property: href
        glob: "http*://www.dropbox.com/{static,password_expired,help/sl,help/vodafone,home*,package_files_uploaded_via_chrome,photos/app_store_link,recover*,sharing/*,sharing/folders*,sharing/files*,requests*,account*,referrals*,downgrade*,developers-v1,developers/downloads/sdks,developers/whats_new,reengageoptout,preview}/**"
        reject: true
      - property: 'href'
        glob: 'http*//blog.dropbox.com/**/_jcr_content/**'
        reject: true
      - property: 'href'
        glob: 'http*//blog.dropbox.com/**/*feed'
        reject: true
      - property: 'path.0'
        glob: '{??-??,??_??,sh,de,fr,es,ja,it,ru,id,pl,ko,ms,t5,lp,en,ep}'
        reject: true
      - "http*//{blog,experience,www}.dropbox.com{*,*/**}"
